---
title: "Homework_5"
author: "Owen Bevis"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

### Load libraries
```{r}
library(tidyverse)
library(tigris)
library(sf)
library(viridis)
library(forcats)
```

### Load data and pick city
```{r}
homicides <- read_csv("../data/homicide-data.csv") %>% 
  filter(city == "Louisville")
```

### Use Tigris to download sub-city information as sf objects.
```{r}
L_tracts <- tracts(state = "KY", 
                   county = "Jefferson", 
                   class = "sf")

L_block_groups <- block_groups(state = "KY", 
                               county = "Jefferson", 
                               class = "sf")

L_county_sub <- county_subdivisions(state = "KY", 
                                    county = "Jefferson", 
                                    class = "sf")

head(L_tracts)
```

### Reorder homicides data 
```{r}
homicides <- homicides %>% 
  mutate(victim_race = factor(victim_race, 
                              levels = c("White", "Black", "Hispanic", "Asian", "Other"))) %>% 
  mutate(victim_race = fct_lump_n(victim_race, n = 3))
```


### Create the plot
```{r}
ggplot() +
  geom_sf(data = L_county_sub, color = "black") +
  #geom_sf(data = L_tracts, color = "black") +
  geom_sf(data = L_block_groups, color = "red") +
  geom_point(data = homicides, 
             aes(x = lon, y = lat, color = victim_race), 
             alpha = 0.3) +
  #scale_color_viridis(name = "test") +
  theme(legend.position = "top") +
  facet_wrap(~ disposition) +
  theme_dark()
```




```{r testing}
# Download tract data for California
tracts <- tracts(state = "CA", cb = TRUE, year = 2020) %>%
  st_as_sf()  # Convert to an sf object for ggplot compatibility

# Dummy data for population density (replace this with real data if available)
set.seed(123)
pop_density_data <- data.frame(
  GEOID = tracts$GEOID,
  pop_density = runif(n = nrow(tracts), min = 100, max = 5000)  # Random values for illustration
)

# Join the population density data to the tracts data
tracts <- tracts %>%
  left_join(pop_density_data, by = "GEOID")

# Plotting the tracts with ggplot
ggplot(data = tracts) +
  geom_sf(aes(fill = pop_density), color = "white", size = 0.1) +
  scale_fill_viridis_c(option = "magma", trans = "log", name = "Population Density") +
  labs(
    title = "Census Tracts in California",
    subtitle = "Colored by Population Density",
    caption = "Data from tigris package, Population Density simulated"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5)
  )
```

```{r testing2}
library(leaflet)

tarrant <- tracts("TX", "Tarrant", cb = TRUE)

leaflet(tarrant) %>%
  addTiles() %>%
  addPolygons(popup = ~NAME)
```

